import { IconUI } from './icon';

export default {
  title: 'IconUI',
  component: IconUI,
  args: {
    name: 'add',
    size: 24,
  },
  argTypes: {
    name: {
      constrol: 'select',
      options: [
        'arrowLeft',
        'arrowSquareLeft',
        'arrowSquareRight',
        'book',
        'briefcase',
        'calendar',
        'checkboxDone',
        'checkboxEmpty',
        'checkboxRemove',
        'chevronDown',
        'chevronRight',
        'chevronUp',
        'clock',
        'count',
        'cross',
        'done',
        'edit',
        'eyeSlash',
        'eye',
        'filterSquare',
        'galleryAdd',
        'galleryEdit',
        'global',
        'home',
        'idea',
        'lifestyle',
        'like',
        'logout',
        'messageText',
        'moon',
        'moreSquare',
        'notification',
        'pallete',
        'plusCircle',
        'radioButtonActive',
        'radioButtonEmpty',
        'request',
        'scroll',
        'scrollSquare',
        'search',
        'share',
        'sort',
        'arrowLeft',
        'arrowSquareLeft',
        'arrowSquareRight',
        'book',
        'briefcase',
        'calendar',
        'checkboxDone',
        'checkboxEmpty',
        'checkboxRemove',
        'chevronDown',
        'chevronRight',
        'chevronUp',
        'clock',
        'count',
        'cross',
        'done',
        'edit',
        'eyeSlash',
        'eye',
        'filterSquare',
        'galleryAdd',
        'galleryEdit',
        'global',
        'home',
        'idea',
        'logo',
      ],
    },
    size: {
      control: 'text',
    },
  },
};

export const Default = {
  args: {
    name: 'logo',
    size: 40,
  },
};
